2022-05-18 08:16:26,670 - INFO - ###########################################
2022-05-18 08:16:26,670 - INFO - /home/php/Documents/Thierry/set_etudiants/Omar RESUTATS/20170907/b3c3y-2017.09.07-16.18.44.737.jpk-nt-force
2022-05-18 08:16:26,670 - INFO - ###########################################
2022-05-18 08:16:26,685 - ERROR - `ydata` must not be empty!
2022-05-18 08:16:26,686 - ERROR - Traceback (most recent call last):
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/controller/controller.py", line 226, in create_dict_curves
    error = new_curve.analyzed_curve(
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 1023, in analyzed_curve
    type_curve = self.curve_return_analyze(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 812, in curve_return_analyze
    type_curve = self.classification(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 941, in classification
    self.fit_linear_classification(
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 829, in fit_linear_classification
    f_parameters = curve_fit(
  File "/home/php/anaconda3/lib/python3.9/site-packages/scipy/optimize/minpack.py", line 748, in curve_fit
    raise ValueError("`ydata` must not be empty!")
ValueError: `ydata` must not be empty!

2022-05-18 08:16:26,686 - INFO - ###########################################
2022-05-18 08:16:28,479 - INFO - ###########################################
2022-05-18 08:16:28,479 - INFO - /home/php/Documents/Thierry/set_etudiants/Omar RESUTATS/20170907/b2c2x-2017.09.07-15.47.40.402.jpk-nt-force
2022-05-18 08:16:28,479 - INFO - ###########################################
2022-05-18 08:16:28,480 - ERROR - `ydata` must not be empty!
2022-05-18 08:16:28,480 - ERROR - Traceback (most recent call last):
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/controller/controller.py", line 226, in create_dict_curves
    error = new_curve.analyzed_curve(
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 1023, in analyzed_curve
    type_curve = self.curve_return_analyze(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 812, in curve_return_analyze
    type_curve = self.classification(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 941, in classification
    self.fit_linear_classification(
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 829, in fit_linear_classification
    f_parameters = curve_fit(
  File "/home/php/anaconda3/lib/python3.9/site-packages/scipy/optimize/minpack.py", line 748, in curve_fit
    raise ValueError("`ydata` must not be empty!")
ValueError: `ydata` must not be empty!

2022-05-18 08:16:28,480 - INFO - ###########################################
2022-05-18 08:16:32,310 - INFO - ###########################################
2022-05-18 08:16:32,310 - INFO - /home/php/Documents/Thierry/set_etudiants/Omar RESUTATS/20170914-E6onPLL/b3c3g-2017.09.14-15.47.33.200.jpk-nt-force
2022-05-18 08:16:32,310 - INFO - ###########################################
2022-05-18 08:16:32,311 - ERROR - 13495
2022-05-18 08:16:32,311 - ERROR - Traceback (most recent call last):
  File "/home/php/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/range.py", line 385, in get_loc
    return self._range.index(new_key)
ValueError: 13495 is not in range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/controller/controller.py", line 226, in create_dict_curves
    error = new_curve.analyzed_curve(
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 1023, in analyzed_curve
    type_curve = self.curve_return_analyze(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 812, in curve_return_analyze
    type_curve = self.classification(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 902, in classification
    jump_time_start_pull = time_data[index_force_max] - \
  File "/home/php/anaconda3/lib/python3.9/site-packages/pandas/core/series.py", line 959, in __getitem__
    return self._get_value(key)
  File "/home/php/anaconda3/lib/python3.9/site-packages/pandas/core/series.py", line 1070, in _get_value
    loc = self.index.get_loc(label)
  File "/home/php/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/range.py", line 387, in get_loc
    raise KeyError(key) from err
KeyError: 13495

2022-05-18 08:16:32,311 - INFO - ###########################################
2022-05-18 08:16:36,533 - INFO - ###########################################
2022-05-18 08:16:36,533 - INFO - /home/php/Documents/Thierry/set_etudiants/Omar RESUTATS/20170914-E6onPLL/b3c3g-2017.09.14-15.53.26.417.jpk-nt-force
2022-05-18 08:16:36,533 - INFO - ###########################################
2022-05-18 08:16:36,533 - ERROR - `ydata` must not be empty!
2022-05-18 08:16:36,533 - ERROR - Traceback (most recent call last):
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/controller/controller.py", line 226, in create_dict_curves
    error = new_curve.analyzed_curve(
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 1023, in analyzed_curve
    type_curve = self.curve_return_analyze(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 812, in curve_return_analyze
    type_curve = self.classification(methods, type_curve)
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 941, in classification
    self.fit_linear_classification(
  File "/home/php/Documents/Thierry/OTAnalysis/otanalysis/model/class_curve.py", line 829, in fit_linear_classification
    f_parameters = curve_fit(
  File "/home/php/anaconda3/lib/python3.9/site-packages/scipy/optimize/minpack.py", line 748, in curve_fit
    raise ValueError("`ydata` must not be empty!")
ValueError: `ydata` must not be empty!

2022-05-18 08:16:36,534 - INFO - ###########################################
